version: "3"

services:
  appdev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./src:/app/src
    ports:
      - "8080:8080"
    environment:
      REACT_APP_API_URI: ${REACT_APP_API_URI}
  app:
    build:
      context: .
      dockerfile: Dockerfile_heroku
    volumes:
      - ./src:/app/src
    ports:
      - "80:80"
    environment:
      PORT: 80
      REACT_APP_API_URI: ${REACT_APP_API_URI}
    
