FROM node:14-alpine as builder

ARG ENV
WORKDIR /app
COPY package.json ./
RUN yarn install
COPY . ./


RUN yarn build
RUN yarn global add serve
WORKDIR /app/build
#Start the application
CMD serve -p 80 -s . 