version: "3"

services:
  appdev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./src:/app/src
    ports:
      - "8080:8080"
    environment:
      REACT_APP_API_URI: http://127.0.0.1:5000
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    volumes:
      - ./src:/app/src
    ports:
      - "80:80"
    environment:
      PORT: 80
    
